Add valueset resource
LibreEHR/core pull request #17
Opened 2016-09-23 14:12 UTC by Leo24

2016-09-23 14:52 UTC, kchapple commented on src/Emr/Eloquent/ProviderData.php
> +        return $this->getId();
get Code should return a string representation of a JSON object that contains data the the client needs, such as this:
`{
    "id": "57e3fa727e77bb26ee9166b0",
    "name": "Bolton Gomez",
    "practiceName": "Lavonne Practice",
    "address": "303 Bay Street, Beyerville, Texas"
  }`

2016-09-23 14:53 UTC, kchapple commented on src/Contracts/PharmacyInterface.php
> +    public function getCode();
This is not needed because the interface method is already defined in ValueSetInterface

2016-09-23 14:54 UTC, kchapple commented on src/Emr/Eloquent/PharmacyData.php
> +        return $this->getId();
The code should return string representation of JSON object. Like this:
`{
    "id": "57e3face1fbe627729dac1ca",
    "name": "Jodie Klein",
    "address": "838 Heyward Street, Ryderwood, Ohio"
  }`

2016-09-23 14:55 UTC, kchapple requested changes

2016-09-26 07:48 UTC, Leo24 commented on src/Contracts/PharmacyInterface.php
> +    public function getCode();
Remove extra code for getCode() method

2016-09-26 07:48 UTC, Leo24 commented on src/Emr/Eloquent/ProviderData.php
> +        return $this->getId();
Amend functionality for code field

2016-09-26 07:48 UTC, Leo24 commented on src/Emr/Eloquent/PharmacyData.php
> +        return $this->getId();
Amend functionality for code field

2016-09-26 13:40 UTC, merged